apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
spec:
  restartPolicy: Never
  containers:
    - name: tensorflow
      image: "tensorflow/tensorflow:devel-gpu"
      command: ["python", "-c", "print('Hello, TensorFlow!')"]
      resources:
        limits:
          cpu: 2
          memory: 4G
          nvidia.com/gpu: 1
        requests:
          cpu: 1
          memory: 2G
          nvidia.com/gpu: 1
